server:
  port: 8090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    click:
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://10.20.42.26:8123/test_springboot
      username: default
      password: default
      initialSize: 50
      maxActive: 100
      minIdle: 10
      maxWait: 6000

# mybatis 配置
mybatis:
  type-aliases-package: cn.com.clickhouse.pojo
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    cn.com.clickhouse.mapper.IndicatorAnalysisMapper: DEBUG

